[package]
name = "server"
version = "0.5.0"
authors = ["The async-rs developers", "quininer <quininer@live.com>"]
edition = "2018"

[dependencies]
async-std = "1.11.0"
async-tls = { path = "../.." }
futures-lite = "1.12.0"
rustls = "0.20.6"
rustls-pemfile = "1.0"
structopt = "0.3.9"
